# -*- coding: utf-8 -*-
"""HW1_Question3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V1yvtCmET0S8gDDGTjb3wb61oVw1SKkN
"""

from keras.datasets import mnist
import numpy as np

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

import matplotlib.pyplot as plt

digit_0 = []
digit_1 = []
digit_2 = []
digit_3 = []
digit_4 = []
digit_5 = []
digit_6 = []
digit_7 = []
digit_8 = []
digit_9 = []

for x in range(len(train_labels)):
  if train_labels[x] == 0:
    digit_0.append(train_images[x])
  if train_labels[x] == 1:
    digit_1.append(train_images[x])
  if train_labels[x] == 2:
    digit_2.append(train_images[x])
  if train_labels[x] == 3:
    digit_3.append(train_images[x])
  if train_labels[x] == 4:
    digit_4.append(train_images[x])
  if train_labels[x] == 5:
    digit_5.append(train_images[x])
  if train_labels[x] == 6:
    digit_6.append(train_images[x])
  if train_labels[x] == 7:
    digit_7.append(train_images[x])
  if train_labels[x] == 8:
    digit_8.append(train_images[x])
  if train_labels[x] == 9:
    digit_9.append(train_images[x])

avg_0 = np.average(digit_0, axis=0)
avg_1 = np.average(digit_1, axis=0)
avg_2 = np.average(digit_2, axis=0)
avg_3 = np.average(digit_3, axis=0)
avg_4 = np.average(digit_4, axis=0)
avg_5 = np.average(digit_5, axis=0)
avg_6 = np.average(digit_6, axis=0)
avg_7 = np.average(digit_7, axis=0)
avg_8 = np.average(digit_8, axis=0)
avg_9 = np.average(digit_9, axis=0)

plt.imshow(avg_0)
plt.show()

plt.imshow(avg_1)
plt.show()

plt.imshow(avg_2)
plt.show()

plt.imshow(avg_3)
plt.show()

plt.imshow(avg_4)
plt.show()

plt.imshow(avg_5)
plt.show()

plt.imshow(avg_6)
plt.show()

plt.imshow(avg_7)
plt.show()

plt.imshow(avg_8)
plt.show()

plt.imshow(avg_9)
plt.show()

